openapi: 3.0.1
info:
  title: Family Context
  description: This is the API definition for Family Context
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1
paths:
  /person/{personId}:
    get:
      summary: Find person by ID
      description: Returns a single person
      operationId: getPersonById
      parameters:
      - name: personId
        in: path
        description: ID of person to return
        required: true
        schema:
          type: string
      - name: sources
        in: query
        description: The data source IDs to query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Person not found
          content: {}
components:
  schemas:

    Person:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        gender:
          type: string
          description: The person's gender. Leave blank for 'unknown'.
          pattern: "[male|female|other]"
        ethnicity:
          type: string
        address:
          type: string
        serviceData:
          $ref: '#/components/schemas/ServiceMap'
      required:
        - id
        - firstName
        - lastName

    ServiceMap:
      type: object
      properties:
        ASC: 
          $ref: '#/components/schemas/AdultSocialCare'
        HOUSING: 
          $ref: '#/components/schemas/Housing'
        POLICE: 
          $ref: '#/components/schemas/Police'
        SCHOOL: 
          $ref: '#/components/schemas/School'

    SourceData:
      type: object
      properties:
        coverageStartDate:
          type: string
          format: date
        coverageEndDate:
          type: string
          format: date
        coverageGeographicArea:
          type: string

    Police:
      allOf:
        - $ref: '#/components/schemas/SourceData'
        - type: object
          properties:
            serviceInvolvement:
              type: string
            policeStation:
              type: string
            contactEmail:
              type: string
            contactNumber:
              type: string
            offences:
              type: array
              items:
                $ref: '#/components/schemas/Offence'

    School:
      allOf:
        - $ref: '#/components/schemas/SourceData'
        - type: object
          properties:
            serviceInvolvement:
              type: string
            schoolName:
              type: string
            admissionType: 
              type: string
            contactName:
              type: string
            contactNumber:
              type: string

    AdultSocialCare:
      allOf:
        - $ref: '#/components/schemas/SourceData'
        - type: object
          properties:
            serviceInvolvement:
              type: string
            leadPractitionerName:
              type: string
            leadPractitionerPhone: 
              type: string
            leadPractitionerEmail:
              type: string
            startDateOfLastInvolvement:
              type: string
              format: date
            mostRecentRecordedInteractionWithService:
              type: string

    Housing:
      allOf:
        - $ref: '#/components/schemas/SourceData'
        - type: object
          properties:
            serviceInvolvement:
              type: string
            leadPractitionerName:
              type: string
            leadPractitionerPhone: 
              type: string
            leadPractitionerEmail:
              type: string
            antiSocialBehaviour:
              type: boolean
            antiSocialBehaviourCaseOpen:
              type: boolean
            rentArrears:
              type: boolean
            rentArrearsCaseOpen:
              type: boolean
            noticeSeekingPossessions:
              type: boolean
            noticeSeekingPossessionsCaseOpen:
              type: boolean
            eviction:
              type: boolean
            evictionCaseOpen:
              type: boolean

    Offence:
      type: object
      properties:
        dateOfOffence:
          type: string
          format: date
        typeOfOffence:
          type: string
        natureOfInvolvement:
          type: string
      
