/**
 * Family Context
 * This is the API definition for Family Context
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Contact from './Contact';
import SourceData from './SourceData';

/**
* The AdultSocialCare model module.
* @module model/AdultSocialCare
* @version 0.0.1
*/
export default class AdultSocialCare {
    /**
    * Constructs a new <code>AdultSocialCare</code>.
    * @alias module:model/AdultSocialCare
    * @class
    */

    constructor() {
                return this;
    }

    /**
    * Constructs a <code>AdultSocialCare</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AdultSocialCare} obj Optional instance to populate.
    * @return {module:model/AdultSocialCare} The populated <code>AdultSocialCare</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdultSocialCare();
            ApiClient.constructFromObject(data, obj, '');
                        if (data.hasOwnProperty('coverageStartDate')) {
                obj['coverageStartDate'] = ApiClient.convertToType(data['coverageStartDate'], 'Date');
            }
            if (data.hasOwnProperty('coverageEndDate')) {
                obj['coverageEndDate'] = ApiClient.convertToType(data['coverageEndDate'], 'Date');
            }
            if (data.hasOwnProperty('coverageGeographicArea')) {
                obj['coverageGeographicArea'] = ApiClient.convertToType(data['coverageGeographicArea'], 'String');
            }
            if (data.hasOwnProperty('serviceInvolvement')) {
                obj['serviceInvolvement'] = ApiClient.convertToType(data['serviceInvolvement'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('startDateOfLastInvolvement')) {
                obj['startDateOfLastInvolvement'] = ApiClient.convertToType(data['startDateOfLastInvolvement'], 'Date');
            }
            if (data.hasOwnProperty('dateOfMostRecentInteraction')) {
                obj['dateOfMostRecentInteraction'] = ApiClient.convertToType(data['dateOfMostRecentInteraction'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {Date} coverageStartDate
    */
    coverageStartDate = undefined;
    /**
    * @member {Date} coverageEndDate
    */
    coverageEndDate = undefined;
    /**
    * @member {String} coverageGeographicArea
    */
    coverageGeographicArea = undefined;
    /**
    * @member {String} serviceInvolvement
    */
    serviceInvolvement = undefined;
    /**
    * @member {module:model/Contact} contact
    */
    contact = undefined;
    /**
    * @member {Date} startDateOfLastInvolvement
    */
    startDateOfLastInvolvement = undefined;
    /**
    * @member {Date} dateOfMostRecentInteraction
    */
    dateOfMostRecentInteraction = undefined;




}
