/**
 * Family Context
 * This is the *DRAFT / WORK IN PROGRESS* API definition for Family Context. This document is currently undergoing rapid change and should not be used as basis for implementation without discussing with the project team. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PaginationInfo model module.
* @module model/PaginationInfo
* @version 0.0.1
*/
export default class PaginationInfo {
    /**
    * Constructs a new <code>PaginationInfo</code>.
    * Search results may include this to specify that a subset of data was sent.
    * @alias module:model/PaginationInfo
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>PaginationInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaginationInfo} obj Optional instance to populate.
    * @return {module:model/PaginationInfo} The populated <code>PaginationInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationInfo();
                                    if (data.hasOwnProperty('totalResults')) {
                obj['totalResults'] = ApiClient.convertToType(data['totalResults'], 'Number');
            }
            if (data.hasOwnProperty('resultsPerPage')) {
                obj['resultsPerPage'] = ApiClient.convertToType(data['resultsPerPage'], 'Number');
            }
            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} totalResults
    */
    totalResults = undefined;
    /**
    * @member {Number} resultsPerPage
    */
    resultsPerPage = undefined;
    /**
    * @member {Number} pageNumber
    */
    pageNumber = undefined;




}
