/**
 * Family Context
 * This is the *DRAFT / WORK IN PROGRESS* API definition for Family Context. This document is currently undergoing rapid change and should not be used as basis for implementation without discussing with the project team. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PaginationDetails model module.
* @module model/PaginationDetails
* @version 0.0.1
*/
export default class PaginationDetails {
    /**
    * Constructs a new <code>PaginationDetails</code>.
    * When making search requests this may be included to specify a subset of data to be sent.
    * @alias module:model/PaginationDetails
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>PaginationDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaginationDetails} obj Optional instance to populate.
    * @return {module:model/PaginationDetails} The populated <code>PaginationDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationDetails();
                                    if (data.hasOwnProperty('resultsPerPage')) {
                obj['resultsPerPage'] = ApiClient.convertToType(data['resultsPerPage'], 'Number');
            }
            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} resultsPerPage
    */
    resultsPerPage = undefined;
    /**
    * @member {Number} pageNumber
    */
    pageNumber = undefined;




}
