/**
 * Family Context
 * This is the API definition for Family Context
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PoliceOffences model module.
* @module model/PoliceOffences
* @version 0.0.1
*/
export default class PoliceOffences {
    /**
    * Constructs a new <code>PoliceOffences</code>.
    * @alias module:model/PoliceOffences
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>PoliceOffences</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PoliceOffences} obj Optional instance to populate.
    * @return {module:model/PoliceOffences} The populated <code>PoliceOffences</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PoliceOffences();
                                    if (data.hasOwnProperty('dateOfOffence')) {
                obj['dateOfOffence'] = ApiClient.convertToType(data['dateOfOffence'], 'Date');
            }
            if (data.hasOwnProperty('typeOfOffence')) {
                obj['typeOfOffence'] = ApiClient.convertToType(data['typeOfOffence'], 'String');
            }
            if (data.hasOwnProperty('natureOfInvolvement')) {
                obj['natureOfInvolvement'] = ApiClient.convertToType(data['natureOfInvolvement'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} dateOfOffence
    */
    dateOfOffence = undefined;
    /**
    * @member {String} typeOfOffence
    */
    typeOfOffence = undefined;
    /**
    * @member {String} natureOfInvolvement
    */
    natureOfInvolvement = undefined;




}
