/**
 * Family Context
 * This is the API definition for Family Context
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Contact from './Contact';
import SourceData from './SourceData';

/**
* The School model module.
* @module model/School
* @version 0.0.1
*/
export default class School {
    /**
    * Constructs a new <code>School</code>.
    * @alias module:model/School
    * @class
    * @extends module:model/SourceData
    */

    constructor() {
        SourceData.call(this);
        
        
    }

    /**
    * Constructs a <code>School</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/School} obj Optional instance to populate.
    * @return {module:model/School} The populated <code>School</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new School();
            
            SourceData.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('serviceInvolvement')) {
                obj['serviceInvolvement'] = ApiClient.convertToType(data['serviceInvolvement'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('schoolName')) {
                obj['schoolName'] = ApiClient.convertToType(data['schoolName'], 'String');
            }
            if (data.hasOwnProperty('admissionType')) {
                obj['admissionType'] = ApiClient.convertToType(data['admissionType'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} serviceInvolvement
    */
    serviceInvolvement = undefined;
    /**
    * @member {module:model/Contact} contact
    */
    contact = undefined;
    /**
    * @member {String} schoolName
    */
    schoolName = undefined;
    /**
    * @member {String} admissionType
    */
    admissionType = undefined;




}
