/**
 * Family Context
 * This is the *DRAFT / WORK IN PROGRESS* API definition for Family Context. This document is currently undergoing rapid change and should not be used as basis for implementation without discussing with the project team. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ServiceSummary model module.
* @module model/ServiceSummary
* @version 0.0.1
*/
export default class ServiceSummary {
    /**
    * Constructs a new <code>ServiceSummary</code>.
    * @alias module:model/ServiceSummary
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>ServiceSummary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceSummary} obj Optional instance to populate.
    * @return {module:model/ServiceSummary} The populated <code>ServiceSummary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceSummary();
                                    if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('lastSynchronised')) {
                obj['lastSynchronised'] = ApiClient.convertToType(data['lastSynchronised'], 'Date');
            }
            if (data.hasOwnProperty('coverageStartDate')) {
                obj['coverageStartDate'] = ApiClient.convertToType(data['coverageStartDate'], 'Date');
            }
            if (data.hasOwnProperty('coverageEndDate')) {
                obj['coverageEndDate'] = ApiClient.convertToType(data['coverageEndDate'], 'Date');
            }
            if (data.hasOwnProperty('dataSource')) {
                obj['dataSource'] = ApiClient.convertToType(data['dataSource'], 'String');
            }
            if (data.hasOwnProperty('recordsAvailable')) {
                obj['recordsAvailable'] = ApiClient.convertToType(data['recordsAvailable'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {Date} lastSynchronised
    */
    lastSynchronised = undefined;
    /**
    * @member {Date} coverageStartDate
    */
    coverageStartDate = undefined;
    /**
    * @member {Date} coverageEndDate
    */
    coverageEndDate = undefined;
    /**
    * @member {String} dataSource
    */
    dataSource = undefined;
    /**
    * @member {Boolean} recordsAvailable
    */
    recordsAvailable = undefined;




}
