/**
 * Family Context
 * This is the *DRAFT / WORK IN PROGRESS* API definition for Family Context. This document is currently undergoing rapid change and should not be used as basis for implementation without discussing with the project team. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceSummary from './ServiceSummary';

/**
* The ServiceDetail model module.
* @module model/ServiceDetail
* @version 0.0.1
*/
export default class ServiceDetail {
    /**
    * Constructs a new <code>ServiceDetail</code>.
    * @alias module:model/ServiceDetail
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>ServiceDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceDetail} obj Optional instance to populate.
    * @return {module:model/ServiceDetail} The populated <code>ServiceDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceDetail();
                                    if (data.hasOwnProperty('summary')) {
                obj['summary'] = ServiceSummary.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], Object);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ServiceSummary} summary
    */
    summary = undefined;
    /**
    * @member {Object} schema
    */
    schema = undefined;
    /**
    * @member {Object} data
    */
    data = undefined;




}
