/**
 * Family Context
 * This is the API definition for Family Context
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdultSocialCare from './AdultSocialCare';
import Housing from './Housing';
import Police from './Police';
import School from './School';

/**
* The ServiceMap model module.
* @module model/ServiceMap
* @version 0.0.1
*/
export default class ServiceMap {
    /**
    * Constructs a new <code>ServiceMap</code>.
    * @alias module:model/ServiceMap
    * @class
    */

    constructor() {
                
    }

    /**
    * Constructs a <code>ServiceMap</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceMap} obj Optional instance to populate.
    * @return {module:model/ServiceMap} The populated <code>ServiceMap</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceMap();
                                    if (data.hasOwnProperty('ASC')) {
                obj['ASC'] = AdultSocialCare.constructFromObject(data['ASC']);
            }
            if (data.hasOwnProperty('HOUSING')) {
                obj['HOUSING'] = Housing.constructFromObject(data['HOUSING']);
            }
            if (data.hasOwnProperty('POLICE')) {
                obj['POLICE'] = Police.constructFromObject(data['POLICE']);
            }
            if (data.hasOwnProperty('SCHOOL')) {
                obj['SCHOOL'] = School.constructFromObject(data['SCHOOL']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AdultSocialCare} ASC
    */
    ASC = undefined;
    /**
    * @member {module:model/Housing} HOUSING
    */
    HOUSING = undefined;
    /**
    * @member {module:model/Police} POLICE
    */
    POLICE = undefined;
    /**
    * @member {module:model/School} SCHOOL
    */
    SCHOOL = undefined;




}
