# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.contact import Contact  # noqa: F401,E501
from swagger_server.models.service_involvement import ServiceInvolvement  # noqa: F401,E501
from swagger_server.models.source_data import SourceData  # noqa: F401,E501
from swagger_server import util


class AdultSocialCare(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, coverage_start_date: date=None, coverage_end_date: date=None, coverage_geographic_area: str=None, contact: Contact=None, service_involvement: ServiceInvolvement=None, start_date_of_last_involvement: date=None, most_recent_recorded_interaction_with_service: str=None):  # noqa: E501
        """AdultSocialCare - a model defined in Swagger

        :param coverage_start_date: The coverage_start_date of this AdultSocialCare.  # noqa: E501
        :type coverage_start_date: date
        :param coverage_end_date: The coverage_end_date of this AdultSocialCare.  # noqa: E501
        :type coverage_end_date: date
        :param coverage_geographic_area: The coverage_geographic_area of this AdultSocialCare.  # noqa: E501
        :type coverage_geographic_area: str
        :param contact: The contact of this AdultSocialCare.  # noqa: E501
        :type contact: Contact
        :param service_involvement: The service_involvement of this AdultSocialCare.  # noqa: E501
        :type service_involvement: ServiceInvolvement
        :param start_date_of_last_involvement: The start_date_of_last_involvement of this AdultSocialCare.  # noqa: E501
        :type start_date_of_last_involvement: date
        :param most_recent_recorded_interaction_with_service: The most_recent_recorded_interaction_with_service of this AdultSocialCare.  # noqa: E501
        :type most_recent_recorded_interaction_with_service: str
        """
        self.swagger_types = {
            'coverage_start_date': date,
            'coverage_end_date': date,
            'coverage_geographic_area': str,
            'contact': Contact,
            'service_involvement': ServiceInvolvement,
            'start_date_of_last_involvement': date,
            'most_recent_recorded_interaction_with_service': str
        }

        self.attribute_map = {
            'coverage_start_date': 'coverageStartDate',
            'coverage_end_date': 'coverageEndDate',
            'coverage_geographic_area': 'coverageGeographicArea',
            'contact': 'contact',
            'service_involvement': 'serviceInvolvement',
            'start_date_of_last_involvement': 'startDateOfLastInvolvement',
            'most_recent_recorded_interaction_with_service': 'mostRecentRecordedInteractionWithService'
        }
        self._coverage_start_date = coverage_start_date
        self._coverage_end_date = coverage_end_date
        self._coverage_geographic_area = coverage_geographic_area
        self._contact = contact
        self._service_involvement = service_involvement
        self._start_date_of_last_involvement = start_date_of_last_involvement
        self._most_recent_recorded_interaction_with_service = most_recent_recorded_interaction_with_service

    @classmethod
    def from_dict(cls, dikt) -> 'AdultSocialCare':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdultSocialCare of this AdultSocialCare.  # noqa: E501
        :rtype: AdultSocialCare
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coverage_start_date(self) -> date:
        """Gets the coverage_start_date of this AdultSocialCare.


        :return: The coverage_start_date of this AdultSocialCare.
        :rtype: date
        """
        return self._coverage_start_date

    @coverage_start_date.setter
    def coverage_start_date(self, coverage_start_date: date):
        """Sets the coverage_start_date of this AdultSocialCare.


        :param coverage_start_date: The coverage_start_date of this AdultSocialCare.
        :type coverage_start_date: date
        """

        self._coverage_start_date = coverage_start_date

    @property
    def coverage_end_date(self) -> date:
        """Gets the coverage_end_date of this AdultSocialCare.


        :return: The coverage_end_date of this AdultSocialCare.
        :rtype: date
        """
        return self._coverage_end_date

    @coverage_end_date.setter
    def coverage_end_date(self, coverage_end_date: date):
        """Sets the coverage_end_date of this AdultSocialCare.


        :param coverage_end_date: The coverage_end_date of this AdultSocialCare.
        :type coverage_end_date: date
        """

        self._coverage_end_date = coverage_end_date

    @property
    def coverage_geographic_area(self) -> str:
        """Gets the coverage_geographic_area of this AdultSocialCare.


        :return: The coverage_geographic_area of this AdultSocialCare.
        :rtype: str
        """
        return self._coverage_geographic_area

    @coverage_geographic_area.setter
    def coverage_geographic_area(self, coverage_geographic_area: str):
        """Sets the coverage_geographic_area of this AdultSocialCare.


        :param coverage_geographic_area: The coverage_geographic_area of this AdultSocialCare.
        :type coverage_geographic_area: str
        """

        self._coverage_geographic_area = coverage_geographic_area

    @property
    def contact(self) -> Contact:
        """Gets the contact of this AdultSocialCare.


        :return: The contact of this AdultSocialCare.
        :rtype: Contact
        """
        return self._contact

    @contact.setter
    def contact(self, contact: Contact):
        """Sets the contact of this AdultSocialCare.


        :param contact: The contact of this AdultSocialCare.
        :type contact: Contact
        """

        self._contact = contact

    @property
    def service_involvement(self) -> ServiceInvolvement:
        """Gets the service_involvement of this AdultSocialCare.


        :return: The service_involvement of this AdultSocialCare.
        :rtype: ServiceInvolvement
        """
        return self._service_involvement

    @service_involvement.setter
    def service_involvement(self, service_involvement: ServiceInvolvement):
        """Sets the service_involvement of this AdultSocialCare.


        :param service_involvement: The service_involvement of this AdultSocialCare.
        :type service_involvement: ServiceInvolvement
        """

        self._service_involvement = service_involvement

    @property
    def start_date_of_last_involvement(self) -> date:
        """Gets the start_date_of_last_involvement of this AdultSocialCare.


        :return: The start_date_of_last_involvement of this AdultSocialCare.
        :rtype: date
        """
        return self._start_date_of_last_involvement

    @start_date_of_last_involvement.setter
    def start_date_of_last_involvement(self, start_date_of_last_involvement: date):
        """Sets the start_date_of_last_involvement of this AdultSocialCare.


        :param start_date_of_last_involvement: The start_date_of_last_involvement of this AdultSocialCare.
        :type start_date_of_last_involvement: date
        """

        self._start_date_of_last_involvement = start_date_of_last_involvement

    @property
    def most_recent_recorded_interaction_with_service(self) -> str:
        """Gets the most_recent_recorded_interaction_with_service of this AdultSocialCare.


        :return: The most_recent_recorded_interaction_with_service of this AdultSocialCare.
        :rtype: str
        """
        return self._most_recent_recorded_interaction_with_service

    @most_recent_recorded_interaction_with_service.setter
    def most_recent_recorded_interaction_with_service(self, most_recent_recorded_interaction_with_service: str):
        """Sets the most_recent_recorded_interaction_with_service of this AdultSocialCare.


        :param most_recent_recorded_interaction_with_service: The most_recent_recorded_interaction_with_service of this AdultSocialCare.
        :type most_recent_recorded_interaction_with_service: str
        """

        self._most_recent_recorded_interaction_with_service = most_recent_recorded_interaction_with_service
