# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_data import SourceData  # noqa: F401,E501
from swagger_server import util


class AdultSocialCare(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, coverage_start_date: date=None, coverage_end_date: date=None, coverage_geographic_area: str=None, service_involvement: str=None, lead_practitioner_name: str=None, lead_practitioner_phone: str=None, lead_practitioner_email: str=None, start_date_of_last_involvement: date=None, most_recent_recorded_interaction_with_service: str=None):  # noqa: E501
        """AdultSocialCare - a model defined in Swagger

        :param coverage_start_date: The coverage_start_date of this AdultSocialCare.  # noqa: E501
        :type coverage_start_date: date
        :param coverage_end_date: The coverage_end_date of this AdultSocialCare.  # noqa: E501
        :type coverage_end_date: date
        :param coverage_geographic_area: The coverage_geographic_area of this AdultSocialCare.  # noqa: E501
        :type coverage_geographic_area: str
        :param service_involvement: The service_involvement of this AdultSocialCare.  # noqa: E501
        :type service_involvement: str
        :param lead_practitioner_name: The lead_practitioner_name of this AdultSocialCare.  # noqa: E501
        :type lead_practitioner_name: str
        :param lead_practitioner_phone: The lead_practitioner_phone of this AdultSocialCare.  # noqa: E501
        :type lead_practitioner_phone: str
        :param lead_practitioner_email: The lead_practitioner_email of this AdultSocialCare.  # noqa: E501
        :type lead_practitioner_email: str
        :param start_date_of_last_involvement: The start_date_of_last_involvement of this AdultSocialCare.  # noqa: E501
        :type start_date_of_last_involvement: date
        :param most_recent_recorded_interaction_with_service: The most_recent_recorded_interaction_with_service of this AdultSocialCare.  # noqa: E501
        :type most_recent_recorded_interaction_with_service: str
        """
        self.swagger_types = {
            'coverage_start_date': date,
            'coverage_end_date': date,
            'coverage_geographic_area': str,
            'service_involvement': str,
            'lead_practitioner_name': str,
            'lead_practitioner_phone': str,
            'lead_practitioner_email': str,
            'start_date_of_last_involvement': date,
            'most_recent_recorded_interaction_with_service': str
        }

        self.attribute_map = {
            'coverage_start_date': 'coverageStartDate',
            'coverage_end_date': 'coverageEndDate',
            'coverage_geographic_area': 'coverageGeographicArea',
            'service_involvement': 'serviceInvolvement',
            'lead_practitioner_name': 'leadPractitionerName',
            'lead_practitioner_phone': 'leadPractitionerPhone',
            'lead_practitioner_email': 'leadPractitionerEmail',
            'start_date_of_last_involvement': 'startDateOfLastInvolvement',
            'most_recent_recorded_interaction_with_service': 'mostRecentRecordedInteractionWithService'
        }
        self._coverage_start_date = coverage_start_date
        self._coverage_end_date = coverage_end_date
        self._coverage_geographic_area = coverage_geographic_area
        self._service_involvement = service_involvement
        self._lead_practitioner_name = lead_practitioner_name
        self._lead_practitioner_phone = lead_practitioner_phone
        self._lead_practitioner_email = lead_practitioner_email
        self._start_date_of_last_involvement = start_date_of_last_involvement
        self._most_recent_recorded_interaction_with_service = most_recent_recorded_interaction_with_service

    @classmethod
    def from_dict(cls, dikt) -> 'AdultSocialCare':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdultSocialCare of this AdultSocialCare.  # noqa: E501
        :rtype: AdultSocialCare
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coverage_start_date(self) -> date:
        """Gets the coverage_start_date of this AdultSocialCare.


        :return: The coverage_start_date of this AdultSocialCare.
        :rtype: date
        """
        return self._coverage_start_date

    @coverage_start_date.setter
    def coverage_start_date(self, coverage_start_date: date):
        """Sets the coverage_start_date of this AdultSocialCare.


        :param coverage_start_date: The coverage_start_date of this AdultSocialCare.
        :type coverage_start_date: date
        """

        self._coverage_start_date = coverage_start_date

    @property
    def coverage_end_date(self) -> date:
        """Gets the coverage_end_date of this AdultSocialCare.


        :return: The coverage_end_date of this AdultSocialCare.
        :rtype: date
        """
        return self._coverage_end_date

    @coverage_end_date.setter
    def coverage_end_date(self, coverage_end_date: date):
        """Sets the coverage_end_date of this AdultSocialCare.


        :param coverage_end_date: The coverage_end_date of this AdultSocialCare.
        :type coverage_end_date: date
        """

        self._coverage_end_date = coverage_end_date

    @property
    def coverage_geographic_area(self) -> str:
        """Gets the coverage_geographic_area of this AdultSocialCare.


        :return: The coverage_geographic_area of this AdultSocialCare.
        :rtype: str
        """
        return self._coverage_geographic_area

    @coverage_geographic_area.setter
    def coverage_geographic_area(self, coverage_geographic_area: str):
        """Sets the coverage_geographic_area of this AdultSocialCare.


        :param coverage_geographic_area: The coverage_geographic_area of this AdultSocialCare.
        :type coverage_geographic_area: str
        """

        self._coverage_geographic_area = coverage_geographic_area

    @property
    def service_involvement(self) -> str:
        """Gets the service_involvement of this AdultSocialCare.


        :return: The service_involvement of this AdultSocialCare.
        :rtype: str
        """
        return self._service_involvement

    @service_involvement.setter
    def service_involvement(self, service_involvement: str):
        """Sets the service_involvement of this AdultSocialCare.


        :param service_involvement: The service_involvement of this AdultSocialCare.
        :type service_involvement: str
        """

        self._service_involvement = service_involvement

    @property
    def lead_practitioner_name(self) -> str:
        """Gets the lead_practitioner_name of this AdultSocialCare.


        :return: The lead_practitioner_name of this AdultSocialCare.
        :rtype: str
        """
        return self._lead_practitioner_name

    @lead_practitioner_name.setter
    def lead_practitioner_name(self, lead_practitioner_name: str):
        """Sets the lead_practitioner_name of this AdultSocialCare.


        :param lead_practitioner_name: The lead_practitioner_name of this AdultSocialCare.
        :type lead_practitioner_name: str
        """

        self._lead_practitioner_name = lead_practitioner_name

    @property
    def lead_practitioner_phone(self) -> str:
        """Gets the lead_practitioner_phone of this AdultSocialCare.


        :return: The lead_practitioner_phone of this AdultSocialCare.
        :rtype: str
        """
        return self._lead_practitioner_phone

    @lead_practitioner_phone.setter
    def lead_practitioner_phone(self, lead_practitioner_phone: str):
        """Sets the lead_practitioner_phone of this AdultSocialCare.


        :param lead_practitioner_phone: The lead_practitioner_phone of this AdultSocialCare.
        :type lead_practitioner_phone: str
        """

        self._lead_practitioner_phone = lead_practitioner_phone

    @property
    def lead_practitioner_email(self) -> str:
        """Gets the lead_practitioner_email of this AdultSocialCare.


        :return: The lead_practitioner_email of this AdultSocialCare.
        :rtype: str
        """
        return self._lead_practitioner_email

    @lead_practitioner_email.setter
    def lead_practitioner_email(self, lead_practitioner_email: str):
        """Sets the lead_practitioner_email of this AdultSocialCare.


        :param lead_practitioner_email: The lead_practitioner_email of this AdultSocialCare.
        :type lead_practitioner_email: str
        """

        self._lead_practitioner_email = lead_practitioner_email

    @property
    def start_date_of_last_involvement(self) -> date:
        """Gets the start_date_of_last_involvement of this AdultSocialCare.


        :return: The start_date_of_last_involvement of this AdultSocialCare.
        :rtype: date
        """
        return self._start_date_of_last_involvement

    @start_date_of_last_involvement.setter
    def start_date_of_last_involvement(self, start_date_of_last_involvement: date):
        """Sets the start_date_of_last_involvement of this AdultSocialCare.


        :param start_date_of_last_involvement: The start_date_of_last_involvement of this AdultSocialCare.
        :type start_date_of_last_involvement: date
        """

        self._start_date_of_last_involvement = start_date_of_last_involvement

    @property
    def most_recent_recorded_interaction_with_service(self) -> str:
        """Gets the most_recent_recorded_interaction_with_service of this AdultSocialCare.


        :return: The most_recent_recorded_interaction_with_service of this AdultSocialCare.
        :rtype: str
        """
        return self._most_recent_recorded_interaction_with_service

    @most_recent_recorded_interaction_with_service.setter
    def most_recent_recorded_interaction_with_service(self, most_recent_recorded_interaction_with_service: str):
        """Sets the most_recent_recorded_interaction_with_service of this AdultSocialCare.


        :param most_recent_recorded_interaction_with_service: The most_recent_recorded_interaction_with_service of this AdultSocialCare.
        :type most_recent_recorded_interaction_with_service: str
        """

        self._most_recent_recorded_interaction_with_service = most_recent_recorded_interaction_with_service
