# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaginationInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_results: int=None, results_per_page: int=None, page_number: int=None):  # noqa: E501
        """PaginationInfo - a model defined in Swagger

        :param total_results: The total_results of this PaginationInfo.  # noqa: E501
        :type total_results: int
        :param results_per_page: The results_per_page of this PaginationInfo.  # noqa: E501
        :type results_per_page: int
        :param page_number: The page_number of this PaginationInfo.  # noqa: E501
        :type page_number: int
        """
        self.swagger_types = {
            'total_results': int,
            'results_per_page': int,
            'page_number': int
        }

        self.attribute_map = {
            'total_results': 'totalResults',
            'results_per_page': 'resultsPerPage',
            'page_number': 'pageNumber'
        }
        self._total_results = total_results
        self._results_per_page = results_per_page
        self._page_number = page_number

    @classmethod
    def from_dict(cls, dikt) -> 'PaginationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginationInfo of this PaginationInfo.  # noqa: E501
        :rtype: PaginationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_results(self) -> int:
        """Gets the total_results of this PaginationInfo.


        :return: The total_results of this PaginationInfo.
        :rtype: int
        """
        return self._total_results

    @total_results.setter
    def total_results(self, total_results: int):
        """Sets the total_results of this PaginationInfo.


        :param total_results: The total_results of this PaginationInfo.
        :type total_results: int
        """

        self._total_results = total_results

    @property
    def results_per_page(self) -> int:
        """Gets the results_per_page of this PaginationInfo.


        :return: The results_per_page of this PaginationInfo.
        :rtype: int
        """
        return self._results_per_page

    @results_per_page.setter
    def results_per_page(self, results_per_page: int):
        """Sets the results_per_page of this PaginationInfo.


        :param results_per_page: The results_per_page of this PaginationInfo.
        :type results_per_page: int
        """

        self._results_per_page = results_per_page

    @property
    def page_number(self) -> int:
        """Gets the page_number of this PaginationInfo.


        :return: The page_number of this PaginationInfo.
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number: int):
        """Sets the page_number of this PaginationInfo.


        :param page_number: The page_number of this PaginationInfo.
        :type page_number: int
        """

        self._page_number = page_number
