# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, status: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param id: The id of this InlineResponse200.  # noqa: E501
        :type id: str
        :param name: The name of this InlineResponse200.  # noqa: E501
        :type name: str
        :param status: The status of this InlineResponse200.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'status': 'status'
        }
        self._id = id
        self._name = name
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse200.


        :return: The id of this InlineResponse200.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse200.


        :param id: The id of this InlineResponse200.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse200.


        :return: The name of this InlineResponse200.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse200.


        :param name: The name of this InlineResponse200.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse200.


        :return: The status of this InlineResponse200.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse200.


        :param status: The status of this InlineResponse200.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
