# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_summary import ServiceSummary  # noqa: F401,E501
from swagger_server import util


class ServiceDetail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, summary: ServiceSummary = None, schema: object = None, data: object = None
    ):  # noqa: E501
        """ServiceDetail - a model defined in Swagger

        :param summary: The summary of this ServiceDetail.  # noqa: E501
        :type summary: ServiceSummary
        :param schema: The schema of this ServiceDetail.  # noqa: E501
        :type schema: object
        :param data: The data of this ServiceDetail.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            "summary": ServiceSummary,
            "schema": object,
            "data": object,
        }

        self.attribute_map = {"summary": "summary", "schema": "schema", "data": "data"}
        self._summary = summary
        self._schema = schema
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> "ServiceDetail":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceDetail of this ServiceDetail.  # noqa: E501
        :rtype: ServiceDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def summary(self) -> ServiceSummary:
        """Gets the summary of this ServiceDetail.


        :return: The summary of this ServiceDetail.
        :rtype: ServiceSummary
        """
        return self._summary

    @summary.setter
    def summary(self, summary: ServiceSummary):
        """Sets the summary of this ServiceDetail.


        :param summary: The summary of this ServiceDetail.
        :type summary: ServiceSummary
        """

        self._summary = summary

    @property
    def schema(self) -> object:
        """Gets the schema of this ServiceDetail.


        :return: The schema of this ServiceDetail.
        :rtype: object
        """
        return self._schema

    @schema.setter
    def schema(self, schema: object):
        """Sets the schema of this ServiceDetail.


        :param schema: The schema of this ServiceDetail.
        :type schema: object
        """

        self._schema = schema

    @property
    def data(self) -> object:
        """Gets the data of this ServiceDetail.


        :return: The data of this ServiceDetail.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this ServiceDetail.


        :param data: The data of this ServiceDetail.
        :type data: object
        """

        self._data = data
